<script>
    export let width = "24";
    export let height = "24";
    export let fill = "{fill}";
    export let customClass = "animatedToast"; // Use a different name to avoid conflict with the class attribute
</script>

<svg
    xmlns="http://www.w3.org/2000/svg"
    width={width}
    height={height}
    viewBox="0 0 24 24"
    {...$$props}
>
    <rect width="7.33" height="7.33" x="1" y="1" {fill}>
        <animate
            id="SVGzjrPLenI"
            attributeName="x"
            begin="0;SVGXAURnSRI.end+0.25s"
            dur="0.75s"
            values="1;4;1"
        />
        <animate
            attributeName="y"
            begin="0;SVGXAURnSRI.end+0.25s"
            dur="0.75s"
            values="1;4;1"
        />
        <animate
            attributeName="width"
            begin="0;SVGXAURnSRI.end+0.25s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="0;SVGXAURnSRI.end+0.25s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
    <rect width="7.33" height="7.33" x="8.33" y="1" {fill}>
        <animate
            attributeName="x"
            begin="SVGzjrPLenI.begin+0.125s"
            dur="0.75s"
            values="8.33;11.33;8.33"
        />
        <animate
            attributeName="y"
            begin="SVGzjrPLenI.begin+0.125s"
            dur="0.75s"
            values="1;4;1"
        />
        <animate
            attributeName="width"
            begin="SVGzjrPLenI.begin+0.125s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="SVGzjrPLenI.begin+0.125s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
    <rect width="7.33" height="7.33" x="1" y="8.33" {fill}>
        <animate
            attributeName="x"
            begin="SVGzjrPLenI.begin+0.125s"
            dur="0.75s"
            values="1;4;1"
        />
        <animate
            attributeName="y"
            begin="SVGzjrPLenI.begin+0.125s"
            dur="0.75s"
            values="8.33;11.33;8.33"
        />
        <animate
            attributeName="width"
            begin="SVGzjrPLenI.begin+0.125s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="SVGzjrPLenI.begin+0.125s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
    <rect width="7.33" height="7.33" x="15.66" y="1" {fill}>
        <animate
            attributeName="x"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="15.66;18.66;15.66"
        />
        <animate
            attributeName="y"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="1;4;1"
        />
        <animate
            attributeName="width"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
    <rect width="7.33" height="7.33" x="8.33" y="8.33" {fill}>
        <animate
            attributeName="x"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="8.33;11.33;8.33"
        />
        <animate
            attributeName="y"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="8.33;11.33;8.33"
        />
        <animate
            attributeName="width"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
    <rect width="7.33" height="7.33" x="1" y="15.66" {fill}>
        <animate
            attributeName="x"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="1;4;1"
        />
        <animate
            attributeName="y"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="15.66;18.66;15.66"
        />
        <animate
            attributeName="width"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="SVGzjrPLenI.begin+0.25s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
    <rect width="7.33" height="7.33" x="15.66" y="8.33" {fill}>
        <animate
            attributeName="x"
            begin="SVGzjrPLenI.begin+0.375s"
            dur="0.75s"
            values="15.66;18.66;15.66"
        />
        <animate
            attributeName="y"
            begin="SVGzjrPLenI.begin+0.375s"
            dur="0.75s"
            values="8.33;11.33;8.33"
        />
        <animate
            attributeName="width"
            begin="SVGzjrPLenI.begin+0.375s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="SVGzjrPLenI.begin+0.375s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
    <rect width="7.33" height="7.33" x="8.33" y="15.66" {fill}>
        <animate
            attributeName="x"
            begin="SVGzjrPLenI.begin+0.375s"
            dur="0.75s"
            values="8.33;11.33;8.33"
        />
        <animate
            attributeName="y"
            begin="SVGzjrPLenI.begin+0.375s"
            dur="0.75s"
            values="15.66;18.66;15.66"
        />
        <animate
            attributeName="width"
            begin="SVGzjrPLenI.begin+0.375s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="SVGzjrPLenI.begin+0.375s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
    <rect width="7.33" height="7.33" x="15.66" y="15.66" {fill}>
        <animate
            id="SVGXAURnSRI"
            attributeName="x"
            begin="SVGzjrPLenI.begin+0.5s"
            dur="0.75s"
            values="15.66;18.66;15.66"
        />
        <animate
            attributeName="y"
            begin="SVGzjrPLenI.begin+0.5s"
            dur="0.75s"
            values="15.66;18.66;15.66"
        />
        <animate
            attributeName="width"
            begin="SVGzjrPLenI.begin+0.5s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
        <animate
            attributeName="height"
            begin="SVGzjrPLenI.begin+0.5s"
            dur="0.75s"
            values="7.33;1.33;7.33"
        />
    </rect>
</svg>
