// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetAllGlyphs() {
  return window['go']['main']['App']['GetAllGlyphs']();
}

export function LoadGlyphsFromJSON(arg1) {
  return window['go']['main']['App']['LoadGlyphsFromJSON'](arg1);
}

export function SearchGlyphs(arg1) {
  return window['go']['main']['App']['SearchGlyphs'](arg1);
}
