// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSearchHistory():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetCategories():Promise<Record<string, number>>;

export function GetFavorites():Promise<Array<main.GlyphMatch>>;

export function GetGlyphs(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.SearchResult>;

export function GetSearchHistory():Promise<Array<string>>;

export function GetStats():Promise<Record<string, any>>;

export function ToggleFavorite(arg1:number):Promise<void>;
