// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetAllGlyphs():Promise<Array<main.Glyph>>;

export function LoadGlyphsFromJSON(arg1:string):Promise<void>;

export function SearchGlyphs(arg1:string):Promise<Array<main.Glyph>>;
