// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSearchHistory() {
  return window['go']['main']['App']['ClearSearchHistory']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetGlyphs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetGlyphs'](arg1, arg2, arg3, arg4);
}

export function GetSearchHistory() {
  return window['go']['main']['App']['GetSearchHistory']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
